[project]
name = "api.tubeinsights"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "beautifulsoup4>=4.12.0",
  "bs4>=0.0.2",
  "fastapi>=0.121.0",
  "playwright>=1.40.0",
  "pytube>=15.0.0",
  "uvicorn>=0.34.0",
]
